import Head from 'next/head';
import { Box } from '@mui/material';
import AboutPart from '@/components/contents/about/blocks/AboutPart';
import ActivityPart from '@/components/contents/about/blocks/ActivityPart';
import EventPart from '@/components/contents/about/blocks/EventPart';
import { client } from '@/configs/microCMS/client';
import { TEvent } from '@/types/events';

export default function About({ events }: { events: TEvent[] }) {
  return (
    <>
      <Head>
        <title>ABOUT | プラタナスの会</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component="main">
        <AboutPart />
        <ActivityPart />
        <EventPart events={events} />
      </Box>
    </>
  );
}

export const getStaticProps = async () => {
  const data = await client.get({
    endpoint: 'events',
  });
  return {
    props: {
      events: data.contents,
    },
  };
};
