import Head from 'next/head';
import { Box } from '@mui/material';
import AboutPart from '@/components/contents/about/blocks/AboutPart';
import ActivityPart from '@/components/contents/about/blocks/ActivityPart';

export default function About() {
  return (
    <>
      <Head>
        <title>ABOUT | プラタナスの会</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component="main">
        <AboutPart />
        <ActivityPart />
      </Box>
    </>
  );
}
