import Head from 'next/head';
import { Box } from '@mui/material';
import JoinPart from '@/components/contents/join/blocks/JoinPart';
import GreetingPart from '@/components/contents/join/blocks/GreetingPart';

export default function Join() {
  return (
    <>
      <Head>
        <title>JOIN | プラタナスの会</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component="main" sx={{ pt: '60px' }}>
        <JoinPart />
        <GreetingPart sx={{ mt: 3, pb: 5 }} />
      </Box>
    </>
  );
}
